### ISSUE TITLE
Will Alexa work on an Old Asterisk version

### ISSUE THREAD

**Issue by gschwiter** [rgrokett/RaspiAsteriskAlexa#13]
Aloha 
I wanted to try an incorporate your Alexa build into a radio communications project that runs an older version of Asterisk. https://www.hamvoip.org/  We use the Pi and Asterisk to run a radio repeater controller and thought your Alexa project would make a nice add-on. Can you also load additional Alexa skills to the development profile. Any guidance you can provide would be helpful I think this will be a great PI project.
Thanks
Gary

**Comment by rgrokett** [comment]
I have used it on v.11 and v.13 of Asterisk just fine (using sudo apt install asterisk), I haven't tried using Alexa skills with it, but their website appears to show support. I assume the skill would need to be activated via the same account used by the Asterisk/Alexa interface, but otherwise, seems possible.  https://developer.amazon.com/alexa-skills-kit

Since this was just a proof-of-concept, the code wasn't optimized, though I have been using it on a dedicated Raspi Zero W for months now and still works w/o modification.   Also, I have not tested it with multiple simultaneous requests, though I believe it would support them. (I know Asterisk on a Raspi3 can run at least 4 active conversations simultaneously.)

I do suggest using a Raspberry 3 instead of Zero as the extra processing speed significantly reduces response time. Also, a wired ethernet connection is much more reliable than wifi.

**Comment by rgrokett** [comment]
I just noticed that the HamVoip system uses Archlinux instead of Raspbian. I am not sure how compatible the code here is with Arch. Most likely, extra dependencies will be needed as Arch is a rather minimal OS. It may also be customized for their particular environment. 

I would suggest only trying the Asterisk/Alexa interface install on a cloned or separate system from your existing, as you could end up making Asterisk incompatible with Allstar's mods.
